
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vr-house
      - PORT=${PORT}
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
